---
- hosts: all
  gather_facts: no
  tasks:
  - name: Ensure Choco is installed
    win_chocolatey:
        name: chocolatey
  - name: Upgrade all installed packages
    win_chocolatey:
        name: all
        state: latest
    register: choco_out
  - debug:
        var: choco_out.stdout_lines
