---
- hosts: all
  gather_facts: no
  tasks:
  - name: Ensure user is present on system
    win_user:
      name: svc_slwinrm
      password: {{ svc_password }}
      state: present
      groups:
        - Administrators
